# Generated by Django 5.2.3 on 2025-09-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="8cFU9I2zhFpkH7EU4lTC9JobHPLiQBLA",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
