# Generated by Django 5.2.3 on 2025-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_auth", "0002_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="A97HM0OlY7LxttwZ3n2jUTsUwIu4qdnL",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
