# Generated by Django 5.2.3 on 2025-09-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_auth", "0003_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="JiN6VVDpjcUg36YwrXwP0xJp2ZJW8qpB",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
