# Generated by Django 5.2.3 on 2025-09-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_auth", "0004_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="s15QGtXwjppmunms1TsvhO4a6AEAVCcY",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
