# Generated by Django 5.2.3 on 2025-09-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_auth", "0005_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="AvpZ2TeeXtBOTqHUVAlW9pZEfGMYSq0C",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
