# Generated by Django 5.2.3 on 2025-09-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_auth", "0006_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="pViQvUJ8CUeWm8WyJbv3tEVn8sqUJ7w4",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
