# Generated by Django 5.2.3 on 2025-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_auth", "0007_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="lHPp9U2WRdrSzQPGJoNjadxtaQR9knrw",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
